### PR TITLE
feat: bank page rework

### LINKED ISSUE #44: Rework bank page layout
The `Bank` page is pretty cluttered at the moment. I want to modify the layout to look more like the original Alberto.

Landing Bank page: List all assets in the same manner we do for Groups (group) and Denoms (factory)

Clicking on an asset should bring us to a list of all activity related to that asset for the current user.

Each asset row should have a `Send` button on the right. The look'n'feel should be like what is done on the Factory page.

Clicking on the `Send` button should bring the `Send` modal on the screen.

We should have a way to display the full transaction history (any asset) for the current user. The original Alberto uses Tabs but perhaps we should use the same approach as in the `Admin` page to make it consistent with the rest of the application? 

Happy to discuss this.

### PR DESCRIPTION
**Pull request by chalabi2**
fixes #44

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `SendModal` component for sending assets through a modal interface.
	- Enhanced `TokenList` with pagination for transaction history and improved balance display.
	- Added `selectedDenom` prop to `IbcSendForm` and `SendForm` for improved token selection flexibility.
	- New `SendTxIcon` added for enhanced user interface.

- **Bug Fixes**
	- Updated validation logic in `SendForm` to ensure token selection is required before submission.

- **Refactor**
	- Reorganized the layout of the `Bank` component for improved user experience, replacing the `SendBox` with `TokenList`.
	- Improved responsiveness and visual consistency in the `HistoryBox` for mobile users.

- **Chores**
	- Removed unnecessary import statements to streamline component dependencies.

### CODE REVIEW

**Comment by chalabi2** [comment]
image

**Review by fmorency — CHANGES_REQUESTED** [review]
Looking good! Thanks!

Minor comments
The mobile menu looks broken



- Is it possible to automatically refresh the history
  - after executing a send transaction?
  - when focusing on the browser window
  - after a delay, e.g., 30s?

**Comment by chalabi2** [comment]
@fmorency yes you can call refetch on useQueries, but since you moved it out of the bank.tsx page and into the history box itself we cant pass it up through props to the sendbox tx hook which use to call it on sucess. But I think I can make it work.

**Comment by chalabi2** [comment]
[fa30e4a](https://github.com/liftedinit/manifest-app/pull/117/commits/fa30e4a5c318429ec9abced465e2d796da48c653) fixes #118 and should take care of all breakpoints for the bank page and its rework

**Pull request merged**
